# Generated by Django 3.0.3 on 2020-02-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competitions',
            new_name='Competition',
        ),
    ]
